# -*- coding: utf-8 -*-
"""BlogsScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rqju_7SAMmVbPElTrLLvSOCTAJJscVZn
"""

!pip install bs4

import urllib

# -*- coding: utf-8 -*- 
from bs4 import BeautifulSoup
import urllib
url = 'https://www.gurujitips.in/case-study-hindi-vs-hinglish-for-blogging/'
html = urllib.request.urlopen(url).read()

soup = BeautifulSoup(html, 'html.parser')
for p in soup.find_all('p'):
    print (p.get_text().encode('utf-8') + "\n\n")

